#!/usr/bin/env python3
# Derive LotAdjuster.Engine/PrimaryForm.resx from Mootilda's LotExpander.resx.
#
# Her form resx mixes the strings her code reads through
# ResourceManager("LotExpander.PrimaryForm") with WinForms-typed data (Point,
# Size, Font, AnchorStyles, ImeMode, a serialized icon) that cannot be
# compiled or loaded on macOS. This keeps, all as plain strings:
#   - the string entries (her texts),
#   - the Visible/Enabled flags her Designer applied with ApplyResources,
#   - the layout values the Mac window uses to draw her form to scale:
#     Location, Size, Font, TextAlign, Multiline, AutoSize.
# Values are copied unchanged (e.g. "105, 38", "Microsoft Sans Serif, 11pt").
#
# Usage: tools/make-form-resx.py <path to her LotExpander.resx>
import re, sys, xml.etree.ElementTree as ET
from xml.sax.saxutils import escape

src = sys.argv[1]
root = ET.parse(src).getroot()
keep = []
for d in root.findall('data'):
    name, typ = d.get('name'), d.get('type')
    v = d.find('value')
    val = v.text if v is not None and v.text is not None else ''
    if name.startswith('>>'):
        continue
    if typ is None and d.get('mimetype') is None:
        keep.append((name, val))
    elif typ and typ.startswith('System.Boolean') and re.search(r'\.(Visible|Enabled|Multiline|AutoSize)$', name):
        keep.append((name, val))
    elif typ and re.match(r'System\.Drawing\.(Point|Size|Font|ContentAlignment)|System\.Windows\.Forms\.HorizontalAlignment', typ) \
            and re.search(r'\.(Location|Size|ClientSize|Font|TextAlign)$', name):
        keep.append((name, val))

out = ['<?xml version="1.0" encoding="utf-8"?>',
       '<!-- GENERATED by tools/make-form-resx.py from Mootilda\'s LotExpander.resx',
       '     (LotAdjuster 3.6). Strings, Visible/Enabled flags and layout values only;',
       '     values unchanged. Do not edit by hand. -->',
       '<root>',
       '  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>',
       '  <resheader name="version"><value>2.0</value></resheader>',
       '  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>',
       '  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>']
for name, val in keep:
    out.append(f'  <data name="{escape(name, {chr(34): "&quot;"})}" xml:space="preserve"><value>{escape(val)}</value></data>')
out.append('</root>')
sys.stdout.write('\n'.join(out) + '\n')
